### ISSUE TITLE
split paragraph function seems not work with pure chinese text

### ISSUE THREAD

**Issue by hyyz17200** [Raychanan/ChatGPT-for-Translation#8]
I am trying with a Chinese subtitle text. This text contains only blank spaces, without any punctuation:

> This model's maximum context length is 4097 tokens. However, your messages resulted in 20465 tokens. Please reduce the length of the messages.
Rate limit hit. Sleeping for 4 seconds.

However, your "really_long_paragraph.txt" works well.

I am attaching the text here:

[longchinese.txt](https://github.com/Raychanan/ChatGPT-for-Translation/files/11026266/longchinese.txt)

**Comment by Raychanan** [comment]
Thank you for providing the context file. However, I am using the NLTk English tokenizer, which is not effective for Chinese text. I suspect that a simple splitting approach will work for your text file, as ChatGPT will likely automatically concatenate your Chinese subtitles. I am not sure if I want to add a feature to handle subtitles.

For now, I think the simplest approach to solve your problem is to simply split your text into paragraphs using some online tools. You can find a list of online tools by searching for "text splitting online tools".

I hope this is helpful!

**Comment by hyyz17200** [comment]
Thank you very much for your reply! I will give a try by following your advice.

**Comment by Raychanan** [comment]
The user has requested the ability to translate subtitles using an unsplitted txt file. While this was not originally part of my envisioned project, it is a reasonable request to some extent. 

I will temporarily close the issue and may consider implementing this feature if more similar requests are received.
